[package]
name = "parse"
version = "0.1.0"
edition = "2021"

[lib]
name = "parse"
path = "src/lib.rs"

[dependencies]
number = { path = "../number" }
ir = { path = "../ir" }
util = { path = "../util" }
