[package]
name = "term_math"
version = "0.1.0"
edition = "2021"

[dependencies]
parse = { path = "parse" }
ir = {path = "ir" }
notification = { path = "notification" }
interpreter = { path = "interpreter" }
