[package]
name = "term_math"
version = "0.1.0"
edition = "2021"

[dependencies]
parse = { path = "parse" }
# notification = { path = "notification" }
# ast = { path = "ast" }
# frontend = { path = "frontend" }
# backend = { path = "backend" }
