[package]
name = "term_math"
version = "0.1.0"
edition = "2021"

[dependencies]
ir = { path = "ir"}
lexer = { path = "lexer" }
# notification = { path = "notification" }
# ast = { path = "ast" }
# frontend = { path = "frontend" }
# backend = { path = "backend" }
