[package]
name = "term_math"
version = "0.1.0"
edition = "2021"

[dependencies]
notification = { path = "notification" }
ast = { path = "ast" }
frontend = { path = "frontend" }
backend = { path = "backend" }
