[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
common = {path = "../common" }
syn = {version = "1.0.92", features = ["full", "parsing"]}
proc-macro2 = "1.0.37"
quote = "1.0.18"
