[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "parser"
path = "src/lib.rs"

[dependencies]
notification = { path = "../../notification" }
lexer = { path = "../lexer" }
validator = { path = "../validator" }
token = { path = "../token" }
ast = { path = "../../ast" }
